### ISSUE TITLE
qannotate using wrong import

### ISSUE THREAD

**Issue by holmeso** [AdamaJava/adamajava#101]
There are a number of classes within `qannotate` that are using `scala.actors.threadpool.Arrays` instead of `java.util.Arrays`.

An example class is `SnpEffMode.java` where in the imports, you can see the call to `scala.actors.threadpool.Arrays`.

The `scala` package comes bundled in the `snpEff` jar file, and so by using the `scala` version of `Arrays` we are coupling our code more tightly with the `snpEff` jar (which should be avoided).

I could well be mistaken here, and in fact the `scala` version of `Arrays` is desired (I must admit that I don't know the difference between the 2 classes), but I suspect that this is an error.

**Comment by ChristinaXu2017** [comment]
I think it was "import java.util.Arrays", don't know when it becomes "scala". when you put mouse to "Arrays.asList", Eclipse popup options like below
 "import java.util.Arrays",
"import scala.actors.threadpool.Arrays;"

I think it is mistake clicked the second one.
