### ISSUE TITLE
Push out thread wait times

### ISSUE THREAD

**Issue by holmeso** [AdamaJava/adamajava#116]
QProfiler failed on a recent run against a large BAM file (hello NIH) due to the following code:

```
// wait for threads to complete
try {
    logger.info("waiting for Producer thread to finish (max wait will be 20 hours)");
    if ( ! pLatch.await(20, TimeUnit.HOURS)) {
        // we've hit the 20 hour limit - shutdown the threads and throw an exception
        producerThreads.shutdownNow();
        consumerThreads.shutdownNow();
        throw new Exception("Producer thread has timed out");
  }
  logger.info("producer thread finished, queue size: " + (q == null ? getQueueSize(queues) : getQueueSize(q) ) );
```

Yes, it ran for more than 20 hours, and then the main thread killed everything.
From the log file:
```
17:38:51.334 [pool-1-thread-1] SEVERE org.qcmg.qprofiler.QProfiler - Exception caught whilst running summarizer for file: /working/genomeinfo/cromwell/cromwell-executions/somaticDnaFastqToMaf/c2d46703-bce5-43cd-9a9e-65d6047fe427/call-testSampleQp/inputs/1800118964/7fde7939-18a9-4e03-b6c4-bb9fad5090f1.bam
java.lang.Exception: Producer thread has timed out
        org.qcmg.qprofiler.bam.BamSummarizerMT.summarize(BamSummarizerMT.java:174)
        org.qcmg.qprofiler.QProfiler$1.run(QProfiler.java:197)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        java.lang.Thread.run(Thread.java:748)
```

We are dealing more and more with large BAM files, and so I think it would be a good idea to push out the `await` times on all our threaded code.
This will require a search through the codebase to find all instances of `await`.
I would suggest doubling the times and see how long before we are back in there doing the same again...

**To Reproduce**
Run `qprofiler` with a single producer, and 3 consumers against a large bam file

**Expected behavior**
It should work.

**Comment by ChristinaXu2017** [comment]
public class Producer implements Runnable {
     …						
     if (++count % 2000000 == 0) {
		…		 
		while (size > (100000 / noOfProducerThreads)) {
 		        Thread.sleep(75);
			size = queue.size();
			if (cLatch.getCount() == 0) {
			           throw new Exception("No consumer threads left, but queue is not empty");
….
