### ISSUE TITLE
qsv install failed

### ISSUE THREAD

**Issue by kbvstmd** [AdamaJava/adamajava#119]
When I install the qsv with ./gradlew :qsv:build,I got the error message like thses :org.qcmg.qsv.util.QSVUtilTest > testGetAnalysisId FAILED
    java.lang.AssertionError at QSVUtilTest.java:172

324 tests completed, 1 failed
:qsv:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qsv:test'.

So how can I solve it? thanks!

**Comment by holmeso** [comment]
It looks like this could be a timezone issue.
Take a look at this SO post for more details: https://stackoverflow.com/questions/6981890/new-datelong-gives-different-results

Quick fix for you is to comment out (prepend the line with `//` ) line 172 from `org.qcmg.qsv.util.QSVUtilTest` and try building again.

Long term fix is to remove this particular test.
