### ISSUE TITLE
qProfiler require new feature to handle Long reads (> 265mers )  

### ISSUE THREAD

**Issue by ChristinaXu2017** [AdamaJava/adamajava#123]
Our current qprofiler can handle long reads up to 265 mers. However, any reads above this size it will throw exceptions, such as java.lang.IndexOutOfBoundsException

One of the main reason is we store kmers scores in one big array. When kmers size is 6 mers the possible 6mers string patterns will be 15625. If a read has 400 mers, the array size will be 400 * 15625.  The length of new long reads are various, it can be a few hundred to half million, even big. Obviously one dimension big array can't cope with such a big size. 

The new feature to handle long reads can be multi-dimension array to store the kmers score. But we not sure how long the long reads can be. For example, there are only a couple long reads in a fastq file, the length is almost chromosome size. then most element value in this new multi-dimension array will be zero or one. 

Another way is we just skip kmers part for qprofiler run when the input is a long reads file.  But we should also investigate whether other functions of qprofiler can support long reads.

**Comment by delocalizer** [comment]
I'm not sure how informative per-base kmer count would be for these very long reads, but a more space-efficient data structure for this might be had by accumulating counts in something like a sparse array or  `ArrayList<HashMap<Integer, Integer>>` where the ArrayList is length 5<sup>n</sup> and (key, value) entries in the map at each index are the base position and the count. That way you only need space for the values you find, not all possible values, and still update counts quickly by addressing the index of the ArrayList and key of the HashMap. You can invert the structure at the end if you want per-base kmer counts.

**Comment by ChristinaXu2017** [comment]
First of all, we should understand why we should count kmers. For short gun reads, we report the kmers pattern based on each read cycle.  For long reads, it will be a different story. It will not only affect the kmers, but also affect seq base and base quality. I think the read cycle is no longer an important element to check read quality.  From a technical point of view, space and speed are not big problems, we can always find a suitable algorithm to match these new features.

**Comment by delocalizer** [comment]
I agree
