### ISSUE TITLE
qannotate to fail gracefully should no reference `.dict` file be supplied

### ISSUE THREAD

**Issue by delocalizer** [AdamaJava/adamajava#19]
Currently if there is no reference dictionary file adjacent to the reference fasta, qannotate in Homopolymer mode fails with NPE:
`java.lang.NullPointerException
    at au.edu.qimr.qannotate.modes.HomoplymersMode.getReferenceBase(HomoplymersMode.java:265)`

**Comment by holmeso** [comment]
Update code so that the following error message is shown rather than a NPE:
`java.lang.IllegalArgumentException: No dict file found for reference file: ....`

**Comment by holmeso** [comment]
Also updated so that if the reference index file is missing, the following message will be displayed:
`java.lang.IllegalArgumentException: No index file found for reference file:...`
