### ISSUE TITLE
Logic for calling MNPs in vcf mode is not correct

### ISSUE THREAD

**Issue by delocalizer** [AdamaJava/adamajava#20]
(my understanding is that) currently in vcf mode, a DNP or TNP is called on the basis of adjacent SNPs having the same unphased GT. This will give false positives when adjacent 0/1 SNPs are actually 0|1 and 1|0. For example at `chr4:49216939-49216940` in the gold standard test sample bam:
![screenshot from 2018-11-28 10-22-52](https://user-images.githubusercontent.com/817809/49120246-9eced880-f2f7-11e8-8203-bb66a3ea24ad.png)
GATK HC called this as:
```
chr4    49216939        .       G       A       614.77  .       AC=1;AF=0.500;AN=2;BaseQRankSum=-0.875;ClippingRankSum=0.000;DP=157;ExcessHet=3.0103;FS=5.356;MLEAC=1;MLEAF=0.500;MQ=51.10;MQRankSum=5.335;QD=3.92;ReadPosRankSum=0.116;SOR=0.343       GT:AD:DP:GQ:PL  0/1:129,28:157:99:643,0,5226
chr4    49216940        .       C       T       1290.77 .       AC=1;AF=0.500;AN=2;BaseQRankSum=-5.868;ClippingRankSum=0.000;DP=157;ExcessHet=3.0103;FS=16.068;MLEAC=1;MLEAF=0.500;MQ=51.22;MQRankSum=8.307;QD=8.22;ReadPosRankSum=-2.988;SOR=0.254     GT:AD:DP:GQ:PL  0/1:102,55:157:99:1319,0,4149
```
and qsnp vcf mode combined these into:
```
chr4    49216939        .       GC      AT      .       .       .       GT:AD:DP:FT:GQ:INF:NNS:OABS:QL  0/1:35,35:70:.:74:.:.:.:1029.77 0/1:102,55:157:.:99:.:.:.:1290.77
```
which is not correct, since by observation none of the reads have both G>A and C>T.

For the record, qsnp standard mode calls this correctly as two adjacent snps, but because gatk mode and std mode disagree at this location none of these calls, individual or compound, make it into the `Pass` vcfs or the maf.

I suggest one of two possible fixes:
1. Make the DNP call depend on (near) matching AD as well as GT — the logic being that if adjacent SNPs actually live on the same reads then the ref/alt counts for both calls must be very similar. In the example above they're clearly quite different. This is obviously a hack, and still prone to false positives when the ref/alt counts on the separate chromosomes are very similar to each other by chance, but is better than the current situation.
2. Since we don't actually have the information in qsnp vcf mode to make a definitive MNP call but qsnp standard mode does, let qsnp vcf mode call adjacent SNPs as both the separate variants _and_ a D/TNP, and let qannotate discard the call(s) that qsnp standard mode did not make when it creates the `Pass` vcfs. No false positives on this one.

**Comment by ChristinaXu2017** [comment]
a very interesting example.  I never see any phased genotypes in our vcf file. There is often an AD keyword after GT, the AD stores the alleles counts eg. 
GT:AD:DP:FT:GQ:INF:NNS:OABS:QL  0/1:35,35:70:.:74:.:.:.:1029.77 0/1:102,55:157:.:99:.:.:.:1290.77

here, AD tells us 35 reads contains the mutation "AT" and 35 reads with reference base "GC". Obviously, these numbers didn't match this example.

**Comment by ChristinaXu2017** [comment]
I guess qSNP vcf mode do find reads contains true MNP.  The value of DP in GATK vcf file is 157 but DP value in qSNP vcf mode is 70.  there may have 87 (157-70) reads contains  0|1 and 1|0.
