### ISSUE TITLE
Supported Reference Genomes Information is Missing

### ISSUE THREAD

**Issue by DarioS** [AdamaJava/adamajava#200]
In the Releases, it appears that some tools work for hg38 and others work for hg19, but it might be a misunderstanding because the text only mentions a genome the tool works with in passing, without explaining if that is the only genome the tool can possibly work with. It would be nice to have a table with ticks in it somewhere that shows which tool supports which reference genome.

**Comment by grendeloz** [comment]
Hi Dario, thanks for your suggestion and we'll take a good look at it.

We have just completed an overhaul of our documentation which you can now find at https://adamajava.readthedocs.io/en/latest/.

In general, our tools are reference agnostic which means as long as the BAM file you specify was aligned against the reference you specify then you should be fine. The one obvious exception is qsignature which requires a file of genomic coordinates for known variants and the list we have is a hg19 list. Creating a GRCh38 genomic location list for qsignature has been on our to-do list for a while but I can't tell you when it will bubble to the top of the to-do list and get done.

Having said all that, most of the tools were designed using hg19 so if there are any places where I've forgotten that we have a hard-wired dependency, it will almost certainly be on hg19.

**Comment by DarioS** [comment]
Can you provide a qMotif configuration file for hg38 on your website or explain where to get the coordinates to be included?
