### ISSUE TITLE
NullPointerException If Output BAM Unspecified

### ISSUE THREAD

**Issue by DarioS** [AdamaJava/adamajava#206]
If I specify `-o` once and provide and XML file name, it errors

```
09:07:21.780 [main] EXEC org.qcmg.motif.Motif - host gadi-login-06.gadi.nci.org.au
qmotif: java.lang.NullPointerException
java.lang.NullPointerException
        at java.io.File.<init>(File.java:279)
        at org.qcmg.motif.JobQueue.<init>(JobQueue.java:109)
        at org.qcmg.motif.Motif.<init>(Motif.java:57)
        at org.qcmg.motif.Motif.main(Motif.java:351)
```

It works fine if `-o` is specified twice, the second time with the BAM file name. It's strange that it has to be specified twice.

**Comment by holmeso** [comment]
Hi, the `qmotif` [wiki page ](https://github.com/AdamaJava/adamajava/wiki/qMotif)has details on how to run the tool. If you follow the instructions there, then you should be able to run the tool without error.
You will note that the wiki page tells the user to specify 2 output options, one for the xml file and the other for the BAM file.

**Comment by DarioS** [comment]
Oh, there is a Wiki and it does provide more specific instructions than what the other website has!
