### ISSUE TITLE
qvisualise fails with an error message

### ISSUE THREAD

**Issue by kimin0402** [AdamaJava/adamajava#224]
**Describe the bug**
I tried running qvisualise with a xml file created from qprofiler2. The program fails with a following error message:

```
Exception in thread "main" java.lang.NullPointerException
        at org.qcmg.qvisualise.report.ReportBuilder.createTAGS(ReportBuilder.java:573)
        at org.qcmg.qvisualise.report.ReportBuilder.buildReport(ReportBuilder.java:87)
        at org.qcmg.qvisualise.report.ReportBuilder.buildReport(ReportBuilder.java:65)
        at org.qcmg.qvisualise.QVisualise.engage(QVisualise.java:58)
        at org.qcmg.qvisualise.QVisualise.setup(QVisualise.java:153)
        at org.qcmg.qvisualise.QVisualise.main(QVisualise.java:97)

```

**To Reproduce**
My java version is 1.8.0_171.
Here is my command from installation to run:

```
git clone https://github.com/AdamaJava/adamajava.git
cd adamajava
./gradlew :qprofiler2:build
tar -xvf qprofiler2/build/distributions/qprofiler2.tar --directory /path/to/qprofiler2
./gradlew :qvisualise:build
tar -xvf qprofiler2/build/distributions/qvisualise.tar --directory /path/to/qvisualise

/path/to/qprofiler2/bin/qprofiler2 -ntP 1 -ntC 4 -validation SILENT \
-input bam_files/cancer.bam \
-index bam_files/cancer.bam.bai \
-output qc_files/cancer_qprofiler2.xml \
-log cancer_qprofiler2.log

/path/to/qvisualise/bin/qvisualise \
-input qc_files/cancer_qprofiler2.xml \
-log cancer_qvisualise.log
```

<details>
  <summary>Full error message</summary>
  
  ```
16:17:07.219 [main] EXEC org.qcmg.qvisualise.QVisualise - Uuid 1cb981a2-7f3b-4943-be80-badd004bf881
16:17:07.219 [main] EXEC org.qcmg.qvisualise.QVisualise - StartTime 2021-01-14 16:17:07
16:17:07.219 [main] EXEC org.qcmg.qvisualise.QVisualise - OsName Linux
16:17:07.220 [main] EXEC org.qcmg.qvisualise.QVisualise - OsArch amd64
16:17:07.220 [main] EXEC org.qcmg.qvisualise.QVisualise - OsVersion 3.10.0-862.el7.x86_64
16:17:07.220 [main] EXEC org.qcmg.qvisualise.QVisualise - RunBy kimin
16:17:07.221 [main] EXEC org.qcmg.qvisualise.QVisualise - ToolName qvisualise
16:17:07.221 [main] EXEC org.qcmg.qvisualise.QVisualise - ToolVersion 41-6f05716
16:17:07.221 [main] EXEC org.qcmg.qvisualise.QVisualise - CommandLine qvisualise -input qc_files/cancer_qprofiler2.xml -log cancer_qvisualise.log
16:17:07.222 [main] EXEC org.qcmg.qvisualise.QVisualise - JavaHome /home/users/cjyoon/tools/jdk1.8.0_171/jre
16:17:07.222 [main] EXEC org.qcmg.qvisualise.QVisualise - JavaVendor Oracle Corporation
16:17:07.222 [main] EXEC org.qcmg.qvisualise.QVisualise - JavaVersion 1.8.0_171
16:17:07.222 [main] EXEC org.qcmg.qvisualise.QVisualise - host bnode15
16:17:07.225 [main] TOOL org.qcmg.qvisualise.QVisualise - running qVisualise with input file: qc_files/cancer_qprofiler2.xml and outputFile: qc_files/cancer_qprofiler2.xml.html
16:17:07.427 [main] INFO org.qcmg.qvisualise.report.XmlReportReader - qprofiler xml file encoding: UTF-8
Exception in thread "main" java.lang.NullPointerException
        at org.qcmg.qvisualise.report.ReportBuilder.createTAGS(ReportBuilder.java:573)
        at org.qcmg.qvisualise.report.ReportBuilder.buildReport(ReportBuilder.java:87)
        at org.qcmg.qvisualise.report.ReportBuilder.buildReport(ReportBuilder.java:65)
        at org.qcmg.qvisualise.QVisualise.engage(QVisualise.java:58)
        at org.qcmg.qvisualise.QVisualise.setup(QVisualise.java:153)
        at org.qcmg.qvisualise.QVisualise.main(QVisualise.java:97)
  ```
</details>

**Expected behavior**
html file output produced from qvisualise

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: CentOS Linux
 - Version: 7 
 - JAVA: JavaVersion 1.8.0_171

**Additional context**
Any idea why this happens?
When running qprofiler2, I set validation to SILENT because my bam file was created from bwa. Also I specified the index file (.bai) because there was an error message saying that the tool couldn't find the index.

**Comment by holmeso** [comment]
Hi, `qvisualise` doesn't work on xml files produced by `qprofiler2`.
If you run `qprofiler` against your bam, that should generate an html file for you.
Please note that `qprofiler` is no longer under active development and will not be as comprehensive in the stats that it collects as `qprofiler2`, but you will, at least, be able to view a html page.

**Comment by kimin0402** [comment]
Thank you @holmeso if `qvisualise` doesn't work on xml files produced by `qprofiler2`, then how can we view the summarized version of the xml file? After running `qprofiler2` is it correct that no html files show up?

**Comment by holmeso** [comment]
> Thank you @holmeso if `qvisualise` doesn't work on xml files produced by `qprofiler2`, then how can we view the summarized version of the xml file? After running `qprofiler2` is it correct that no html files show up?

You are right, `qprofiler2` produces a xml file and no html file. We have in-house software that creates a pdf file from `qprofiler2` xml files, but this is not publicly available.

If you use the original `qprofiler`, you will get html output (via `qvisualise`), but this tool is no longer maintained.

**Comment by kimin0402** [comment]
Thanks again @holmeso for your answer. However, I'd like to point out that an html file created from `qprofiler` does not show results anymore. This is because some of the javascript files it uses from the internet are no longer supported. For example links like
 ```
http://systemsbiology-visualizations.googlecode.com/svn/trunk/src/main/js/load.js
```
is no longer available, nevertheless it is used in an html file created by `qprofiler`. I have to manually change unavailable .js files to working .js files in order to view the html file.

Of course, I'm not asking for an update for `qprofiler`, as you specified that it is no longer maintained. Since `qprofiler` does not create proper html file and `qprofiler2` can't be used without in-house scripts, I guess I'll have to look for another tool for summarizing bam QC information. Thank you once again for your kind answer.
