### ISSUE TITLE
qmotif.ini

### ISSUE THREAD

**Issue by sunna-0423** [AdamaJava/adamajava#318]
I have a problem with the definition of telomere location in qmotif.ini, could you please help me ?

Suppose there are three positions in chr1p that contain telomere sequences (28074001-28074600,66019501-66019800,91923901-91924200), the first position is set to chr1p: 28074001-28074600, the second position is set to chr1xA: 66019501-66019800, the third position is set to chr1xB: 91923901-91924200, but if there are multiple positions on other chromosomes like this, how do I represent them when I run out of 26 letters?

**Comment by holmeso** [comment]
The name that you provide for the positions can be any unique string.
eg.
```
name1    chr1:28074001-28074600 
name2    chr1:66019501-66019800 
foo    chr1:91923901-91924200
bar    chr1:222222222-222222233
...
```

**Comment by sunna-0423** [comment]
> The name that you provide for the positions can be any unique string. eg.
> 
> ```
> name1    chr1:28074001-28074600 
> name2    chr1:66019501-66019800 
> foo    chr1:91923901-91924200
> bar    chr1:222222222-222222233
> ...
> ```
I see, thank you .

**Comment by sunna-0423** [comment]
Also,I want to make sure that the ini file you prvided in github is hg19, right?

**Comment by holmeso** [comment]
> Also,I want to make sure that the ini file you prvided in github is hg19, right?

yes, well its GRCh37 (ie. has "chr" at the start of the chromosome names)

**Comment by sunna-0423** [comment]
> 
I am so appreciate it！

**Comment by hejing3283** [comment]
Could you provide a ini file for hg38? 
The telomere length I got from UCSC is 1kb per region. not consistent with the hg19 ini file provide. 
Thanks a lot! 

Best
Jing

**Comment by holmeso** [comment]
> Could you provide a ini file for hg38? The telomere length I got from UCSC is 1kb per region. not consistent with the hg19 ini file provide. Thanks a lot!
> 
> Best Jing

Hi,
I put the regions from the GRCh37 `qmotif` ini file into the [liftover](https://genome.ucsc.edu/cgi-bin/hgLiftOver) tool, and converted them to GRCh38.
Here they are:
```
chr1p   chr1:10001-12464
chr1q   chr1:248943708-248946421
chr2p   chr2:10001-12592
chr2q   chr2:242146750-242148749
chr2xA  chr2:242181358-242183529
chr3p   chr3:18323-20322
chr3q   chr3:198233559-198235558
chr3xB  chr3:198170705-198176526
chr4p   chr4:10001-12193
chr4q   chr4:190120458-190123120
chr5p   chr5:10001-13806
chr5q   chr5:181476259-181478258
chr6p   chr6:60001-62000
chr6q   chr6:170743979-170745978
chr7p   chr7:10001-12238
chr7q   chr7:159333868-159335972
chr8p   chr8:60001-62000
chr8q   chr8:145076636-145078635
chr9p   chr9:10001-12359
chr9q   chr9:138260981-138262980
chr10p  chr10:14061-16061
chr10q  chr10:133785144-133787421
chr11p  chr11:60001-62000
chr11q  chr11:135074564-135076621
chr12p  chr12:43740-45739
chr12q  chr12:133262872-133265308
chr12xC chr12:10001-12582
chr13p  chr13:18445861-18447860
chr13q  chr13:114342403-114344402
chr14p  chr14:18243524-18245523
chr14q  chr14:106879333-106881349
chr15p  chr15:19794748-19796747
chr15q  chr15:101978766-101981188
chr16p  chr16:10001-12033
chr16q  chr16:90226345-90228344
chr17p  chr17:150208-152207
chr17q  chr17:83245442-83247441
chr18p  chr18:10001-12621
chr18q  chr18:80256343-80259271
chr19p  chr19:60001-62000
chr19q  chr19:58605455-58607615
chr20p  chr20:79360-81359
chr20q  chr20:64332167-64334166
chr21p  chr21:8522361-8524360
chr21q  chr21:46697876-46699982
chr22p  chr22:15926017-15927980
chr22q  chr22:50804138-50806137
chrXp   chrX:10001-12033
chrXq   chrX:156028068-156030894
chrYp   chrY:10001-12033
chrYq   chrY:57214588-57217414
```

Please feel free to update your ini file with these updated coordinates.
Note that we have not tested this, and it would be very useful to get your feedback!
Thanks for your help!
