### ISSUE TITLE
Request for qmotif Version Tag: March 31, 2021 Release (V3)

### ISSUE THREAD

**Issue by Ansepil** [AdamaJava/adamajava#345]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to know the version tag for the current release of qmotif (2021-03-31, V3). I'm having difficulty with version follow-up due to not knowing the version tag.

On the https://adamajava.readthedocs.io/en/latest/qmotif/ link, for V1 and V2, I can check version tags like v1.0, v1.2, etc. However, I cannot find the tag for V3 - the current version.

The command to check the current version of qmotif is as follows:
```
java -jar qmotif.jar --version
qmotif, version 130-205fbf86
```

However, it seems this version is based on the GitHub commit (https://github.com/AdamaJava/adamajava/blob/master/version.txt) rather than the qmotif version itself.

The qmotif version in the XML output is also the same:
```
<qmotif version="130-205fbf86">
```

**Describe the solution you'd like**
I would appreciate it if you could provide the version tag for the current release of qmotif (2021-03-31) or inform me of how to find it. Thank you.

**Comment by holmeso** [comment]
Hi, thanks for your request.
In the old days, we would version each of the tools within `adamajava`. A few years ago we changed our approach, and now version the top level project (`adamajava`) only. This is similar to other bioinformatics tools suites (picard-tools for eaxample).
And so, the current version of `qmotif` is indeed `130-205fbf86`
Thanks again!

**Comment by Ansepil** [comment]
Thank you for your response. I appreciate it, and my question has been resolved.
