### ISSUE TITLE
Query the values for MIN threshold in qsnp

### ISSUE THREAD

**Issue by delocalizer** [AdamaJava/adamajava#47]
In `org.qcmg.snp.util.GenotypeUtil` we have:
`MUTATION_IN_NORMAL_MIN_COVERAGE = 3`
`MUTATION_IN_NORMAL_MIN_PERCENTAGE = 5`
The min percentage in particular seems too low in practice, since for 20x coverage (not uncommon for a control sample) this means that a sequencing error on just one read in the normal will trigger the MIN annotation for an otherwise ok SNP call at that location in the test sample, and the call will fail filtering.
That this isn't just a theoretical problem can be seen by using qasim to generate mutations on simulated HiSeq2500 reads. For the example in https://genomeinfo.qimrberghofer.edu.au/svn/genomeinfo/adhoc/conradL/work_record/20181213_wf_evaluation, there are 14 false negative somatic calls (true mutations, uncalled) on chr1, three of them are because of this MIN annotation and all of them caused by a sequencing error on a single read.
It should also be considered that the issue will be more severe for noisier sequencing tech e.g. XTen.
Even from a biological p.o.v. it's hard to justify a 5% threshold for a normal control when you'd expect something close to either 50% or 100%. There would certainly be a case for a low threshold when the control sample was not normal, e.g. precancerous lesion or other clonal tissue from the Barrett's study, but I imagine that should be the unusual case, not the default. Perhaps this should be a tunable parameter in the qsnp configuration, with a reasonably high default e.g. 20% but settable to something lower for special cases?

**Comment by holmeso** [comment]
It is the compound snps that are using these values for the `MIN` annotation.
Regular snps have this added in `qannotate`'s `ConfidenceMode`, where we have the following defaults:
```
public static final int MUTATION_IN_NORMAL_MIN_PERCENTAGE = 3;					// setting this to 3 to mirror existing prod pipeline - was 5
public static final int MUTATION_IN_NORMAL_MIN_COVERAGE = Integer.MAX_VALUE;		// set this to Integer.MAX_VALUE so that we are purely using percentage
```
These values are overridable by setting the following options when running `qannotate`:
```
minCutoff
minPercentage
```

I think the best way to proceed is to remove the code in `qsnp` that populates the `MIN` flag for compound snps, and have `qannotate` handle it instead.

**Comment by holmeso** [comment]
More than happy to change the defaults in `qannotate`'s `ConfidenceMode` but this needs to be driven by the end users.

**Comment by delocalizer** [comment]
> More than happy to change the defaults in `qannotate`'s `ConfidenceMode` but this needs to be driven by the end users.

Totally. The "query" of the issue title is for the biologists

**Comment by holmeso** [comment]
At the Bribie Island retreat, Nic said she was happy for this threshold to rise so that at least 2 reads bearing the mutation need to be present for the MIN flag to be triggered.
Need to double check that this is `max(2, 3%) `rather than just 2
