### ISSUE TITLE
Add MGIseq2000 as a Platform for qSV

### ISSUE THREAD

**Issue by bioInfo25** [AdamaJava/adamajava#60]
Can MGIseq2000 be added as a valid platform for qSV. 

The GENOMIQA Grafli entry for this is:
UUID:   mgiseq2000
label:  MGIseq2000

**Comment by holmeso** [comment]
Need to check to see if the default configuration of the paired end reads is the same as illumina (first read on forward, second on reverse)

**Comment by holmeso** [comment]
> Need to check to see if the default configuration of the paired end reads is the same as illumina (first read on forward, second on reverse)

Have verbal confirmation (from 2 different sources) that this is indeed the case

**Comment by holmeso** [comment]
Are there any other BGI platforms that should be added?

**Comment by bioInfo25** [comment]
Yes. BGISeq500

**Comment by holmeso** [comment]
Do you know what platform number `bgi` would translate to in the `dcc` files?
eg. `solid` is 4, `illumina` is 40.
I'll set it to 99 for now...

**Comment by bioInfo25** [comment]
I think the closest is 81 Complete Genomics
That company got bought out by BGI
if we are to make it BGI specific, it might have to be a new one

**Comment by holmeso** [comment]
> I think the closest is 81 Complete Genomics
> That company got bought out by BGI
> if we are to make it BGI specific, it might have to be a new one

I'll set it to 81

**Comment by holmeso** [comment]
Don't think the platform number for `bgi` matters - `qsv` writes out `-999` for all platforms...
